services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pomodoro_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    networks:
      - pomodoro_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pomodoro_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:8000
    networks:
      - pomodoro_network
    command: npm run dev -- --host

networks:
  pomodoro_network:
    driver: bridge
